const places: string[] = [
  'Hospital',
  'Praia',
  'Cidade',
  'Fazenda',
  'Riacho',
  'Lagoa',
  'Aeroporto',
  'Escola',
  'Banco',
  'Mercado',
  'Feira',
  'Deserto',
  'Cascata',
  'Cachoeira',
  'Balada',
  'Cassino',
  'Hotel',
  'Estação de Trem',
  'Parque',
  'Agência dos correios',
  'Biblioteca',
  'Restaurante',
  'Cinema',
  'Zoológico',
  'Igreja',
  'Padaria',
  'Livraria',
  'Farmácia',
  'Casa',
  'Apartamento',
  'Cafeteria',
  'Barbeiro',
  'Banheiro Químico',
  'Garagem',
  'Museu',
  'Posto de bombeiros',
  'Delegacia de polícia',
  'Estádio de futebol',
  'Campo de golfe',
  'Quadra de basquete',
  'Presídio',
  'Posto de pedágio',
  'Açougue',
  'Alfaiataria',
  'Petshop',
  'Universidade Federal do Rio Grande',
  'Centro de Ciências Computacionais',
];

export default places;
